### ISSUE TITLE
Add it to official bids-apps list

### ISSUE THREAD

**Issue by yarikoptic** [PeerHerholz/BIDSonym#11]
### Summary

Missing from 
http://bids-apps.neuroimaging.io/apps/

Might close https://github.com/BIDS-Apps/bids-apps.github.io/issues/12

**Comment by PeerHerholz** [comment]
Thx for the pointer. @rxqx and I were actually talking with @chrisgorgo about moving it to the `BIDS-Apps` repo, but didn't really follow up on this. We could do so now, if everyone is okay with it? It would also be fine with me to leave it as it is, but having it under the `BIDS-Apps` repo would reflect the community driven development of `BIDSonym` better.

**Comment by yarikoptic** [comment]
If @chrisgorgo blesses such move I could assist to make it happen. Cheers

**Comment by rxqx** [comment]
It's ok with me!

**Comment by PeerHerholz** [comment]
@yarikoptic added `BIDSonym` to the `BIDS-Apps` website (thanks for that) and I'll tackle some issues regarding versioning, tests, etc. now.
