### ISSUE TITLE
anonymize / remove metadata

### ISSUE THREAD

**Issue by PeerHerholz** [PeerHerholz/BIDSonym#13]
### Summary

@Remi-Gau reminded of an additionally `BIDSonym` functionality that was discussed a while back, that is the possibility to also anonymize and/or delete certain parts of the metadata (e.g. measurement site, etc.). For example, users could provide a list of metadata to be anonymized and/or removed. How is everyone feeling about this? 
I would suggest to gather the metadata that could/should be able to be anonymized and/or removed in this thread.

**Comment by Remi-Gau** [comment]
I think that the lowest hanging fruits are the stuff in the BIDS specs regarding dates for example. 

Also I think that some DICOM converters might leave some info in files headers regarding sites, patient names, dates and so on it would be good to look for.

My guess is that it will be hard to have filters that strike the best specificity / sensitivity filters on specific  string patterns in the metadata. So maybe have something that at least throws warning about potential problems and lets the user decide: a bit like the BIDS validator.

**Comment by PeerHerholz** [comment]
That's a brilliant idea @Remi-Gau, thx. So, we could extend BIDSonym to include some sort of validator (actually a good point to include the BIDSvalidator, will do that) that checks for metadata in the header and sidecar files, putting the result in a small text file for the user to evaluate. Maybe we could also include some sort of "pointers" to potentially problematic metadata as you mentioned. With that BIDSonym could have a two-fold functionality: check metadata & anonymize. What do you think?

**Comment by Remi-Gau** [comment]
Yup exactly. That was the gist of the idea I had on my to do list.

**Comment by Remi-Gau** [comment]
2 dicom fields that were appearing in my headers for exampls were:
- `AcquisitionDateTime` 
- `PatientName`

But I suspect that looking through a list of the common DICOM fields should help us target some potential other supects to watch out for.

**Comment by PeerHerholz** [comment]
removing of meta-data files was implemented [here](https://github.com/PeerHerholz/BIDSonym/commit/f8f969a50f9536eb8870fb9d3c9e4a813b8b90a2). will work on validator, etc. now.

**Comment by PeerHerholz** [comment]
check data for potentially sensitive information and outputting results as image or json specific .csv was implemented [here](https://github.com/PeerHerholz/BIDSonym/commit/882d810c44defc44d0f834145ab0b04be190727b#diff-76cee3aac5377e3bdeb5cc63d32ddaae).

**Comment by PeerHerholz** [comment]
The [BIDS-validator](https://github.com/bids-standard/bids-validator) was added in this [PR](https://github.com/PeerHerholz/BIDSonym/commit/4cda9083db4fdc3d7e0306534462dad8b94d2f8a).

I'll close this issue for now. In case of additions and/or changes it can be reopened.
