### ISSUE TITLE
multimodal

### ISSUE THREAD

**Issue by CPernet** [PeerHerholz/BIDSonym#14]
### Summary

have option to deface other than T1w, eg. T2w

### Script/Workflow details

_(I do that with SPM from mrideface T1w)_

generate mask (img - defaced)
coreg T1w to img 
apply transform to mask
apply mask img

**Comment by PeerHerholz** [comment]
Thx for bringing this up @CPernet! 
So far I used the lazy method, applying the same tools to `T1w` and e.g., `T2w`, but you're approach is of course way more appropriate. 
I'll include a small `nipype workflow` that conducts the processing steps you mentioned in cases where there's multimodal data.

**Comment by PeerHerholz** [comment]
A working (and build passing) function has been added [here](https://github.com/PeerHerholz/BIDSonym/commit/5c0ea9dca1fce977c149b9a86dd291931651e4c1).

I'll close this issue for now, but in case there are problems/additions/etc. it can always be reopened.
