### ISSUE TITLE
Link to SingularityHub to provide ready-to-use singularity container

### ISSUE THREAD

**Issue by yarikoptic** [PeerHerholz/BIDSonym#24]
There is a Singularity recipe generated and shipped but documentation instructs to build singularity container out from docker container.  Although should work (about to try ;)), it is more turnkey (and also might more reproducible) to just provide a singularity container from https://singularity-hub.org/ - just link you repo on it, and since Singularity file is already here, it should build a singularity container for reuse.

**Comment by yarikoptic** [comment]
one possible gotcha when we were trying to "pull" singularity container from docker hub -- we ran out of space in `/tmp` now requiring a dance to be made

**Comment by PeerHerholz** [comment]
Should be [here](https://singularity-hub.org/collections/4645) now, thus closing this issue. Please feel free to re-open in case there are problems.

**Comment by yarikoptic** [comment]
Fixed by adding a badge to README.rst
