### ISSUE TITLE
Needs a refresher build? bids-validator is old 1.2.3 whenever 1.54 is current release

### ISSUE THREAD

**Issue by yarikoptic** [PeerHerholz/BIDSonym#25]
```
$ singularity exec envs/bidsonym_latest.sif bids-validator --version
1.2.3
```
this is a singularity container pulled from docker image as of today

**Comment by PeerHerholz** [comment]
The `bids-validator` version was chosen on purpose as others failed during the implementation. Will look into it.

**Comment by PeerHerholz** [comment]
`bids-validator` was updated to 1.5.4 via this [commit](https://github.com/PeerHerholz/BIDSonym/commit/62e46164b965ff6e0705460205acc0d998e63d46).
