### ISSUE TITLE
at least warn whenever incorrect/missing participant id is specified

### ISSUE THREAD

**Issue by yarikoptic** [PeerHerholz/BIDSonym#26]
I have misread `--help` and specified sub id with `sub-` prefix.

```
smaug:~/proj/nuisance/data/dbic-deid$ envs/bidsonym_latest.sif sourcedata participant --participant_label=sub-sid000003 --deid pydeface
Making sure the input data is BIDS compliant (warnings can be ignored in most cases).
This dataset appears to be BIDS compatible.

        Summary:                   Available Tasks:        Available Modalities: 
        1115 Files, 11.56MB                                T1w                   
        206 - Subjects                                                           
        370 - Sessions                                                           


	If you have any questions, please post on https://neurostars.org/tags/bids.

smaug:~/proj/nuisance/data/dbic-deid$ echo $?
0
```

as you can see -- nothing really happened and even no non-0 exit code

**Comment by PeerHerholz** [comment]
Should be addressed via [this commit](https://github.com/PeerHerholz/BIDSonym/commit/81ae1fe5852ec539bba87abecbc9c08f3e27df95). If the specified `participant label` is not in the list of included participants, the process stops and provides the label of the missing `participant`.

**Comment by yarikoptic** [comment]
invaluable advice from yours truly: use `Closes #XXX` (not `addresses`) statement in your commit or PR messages etc to avoid the need for the manual closing of issues etc.  See e.g. historical note from 2013: https://github.blog/2013-01-22-closing-issues-via-commit-messages/ ;-)
