### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by KirstieJane** [PeerHerholz/BIDSonym#3]
Hi everyone! I was chatting on slack with @rxqx and she mentioned adding a code of conduct.

The one from the BIDS Starter Kit is pretty nice - I can add that to the repo in a pull request if you'd like?

It will need a little editing because you'll need to say *who* will be the person to contact (it doesn't make sense for it to be me!) but you can do that in the PR I think 👾 

Let me know if this sounds like a good plan and I'll open the PR ✨

**Comment by PeerHerholz** [comment]
@rxqx, @KirstieJane, thank you both very much. Looks great!

@rxqx: if you don't want to put your email address and/or website in the repo, that would be fine for me. If folks want to reach out they can contact me and I can forward it to you. Most likely they'll open an issue and/or PR anyway through which you would be in the loop automatically. 

If that's okay for everyone, I would close this issue.

**Comment by rxqx** [comment]
that solution works for me!
