### ISSUE TITLE
docker hub needs a tagged release

### ISSUE THREAD

**Issue by yarikoptic** [PeerHerholz/BIDSonym#31]
I have made bidsonym listed among bids-apps, only then to realize that there is no tagged release on docker hub, see http://bids-apps.neuroimaging.io/apps/

could you please tag some release on your docker hub (not yet sure if anything would needed to be done on bids-apps frontend to detect that)

Thanks in advance

**Comment by PeerHerholz** [comment]
tagged builds are now available, as e.g. visible [here](https://hub.docker.com/repository/docker/peerherholz/bidsonym/tags?page=1).
