### ISSUE TITLE
Please release 0.0.3

### ISSUE THREAD

**Issue by yarikoptic** [PeerHerholz/BIDSonym#38]
I think the initial issue reported in #23 was addressed.  I ran the "latest" docker image (converted to singularity) and it didn't choke, moreover produced reproducible output which is great!

@PeerHerholz Would you be so kind to tag current master as 0.0.3 (or 0.1? ;)) release?  That would allow me to update its copy within ReproNim/containers etc

**Comment by PeerHerholz** [comment]
Ahoi hoi,

I'm very sorry for the late reply and absence from this repo.
I'm currently adding and testing a few things which will be included in `0.0.3` and be up asap.

**Comment by yarikoptic** [comment]
was addressed AFAIK

❯ git show v0.0.5
tag v0.0.5
Tagger: Peer Herholz <herholz.peer@gmail.com>
Date:   Sat Aug 28 11:02:20 2021 +0200

This release includes a variety of bug fixes and JOSS review process.

commit 89b5443327cbd3be1919171d030aaa70daa0d592 (tag: v0.0.5)
Author: Peer Herholz <herholz.peer@gmail.com>
Date:   Sat Aug 28 11:01:44 2021 +0200
