### ISSUE TITLE
Bidsonym single session

### ISSUE THREAD

**Issue by araikes** [PeerHerholz/BIDSonym#40]
I've tracked down the primary issue in #39 to this line:

https://github.com/PeerHerholz/BIDSonym/blob/fdc969cd10b49a5fc3ffa44a2f6cbbdd2268fc9a/bidsonym/run_deeid.py#L117

In single-session datasets, this crashes because the sessions iterator is empty.

**Comment by PeerHerholz** [comment]
Ahoi hoi @araikes,

I'm super sorry for the late reply and the absence from this repo.
Thank you very much for bringing this issue up. I actually solved this problem a while back, but didn't
push the changes yet. This will happen asap.
