### ISSUE TITLE
minor typos and errors in JOSS manuscript

### ISSUE THREAD

**Issue by neuromusic** [PeerHerholz/BIDSonym#53]
related to JOSS Review at https://github.com/openjournals/joss-reviews/issues/3169

- typo, line 16 of draft PDF: "par-ticipant" ➡️ "participant"
- typo, line 17 of draft PDF: "Re-view" ➡️ "Review"
- typo, line 45 of draft PDF: "pypi" ➡️ "PyPI"
- error, line 53 of draft PDF: "??"
- typo, line 91 of draft PDF: "Of" ➡️ "of"

**Comment by PeerHerholz** [comment]
Hi @neuromusic,

thanks so much for the feedback. I addressed and fixed these issues via [a629ae2](https://github.com/PeerHerholz/BIDSonym/commit/a629ae2cb2ac0b9d914a7ecd00cccd936d35aef6). I'll recreate the updated PDF in the [review thread](https://github.com/openjournals/joss-reviews/issues/3169).
