### ISSUE TITLE
improvements to installation documentation

### ISSUE THREAD

**Issue by neuromusic** [PeerHerholz/BIDSonym#54]
(related to JOSS Review at openjournals/joss-reviews#3169)

the installation instructions suggest `docker pull peerherholz/bidsonym:version` to install, however "version" is invalid. this should be updated to a command that can be copied and pasted, like `docker pull peerherholz/bidsonym` or `docker pull peerherholz/bidsonym:latest`

similarly, there's a typo in the markup for the code to pull from singularity at https://peerherholz.github.io/BIDSonym/installation.html#directly-pulling-from-singularity-hub

**Comment by PeerHerholz** [comment]
Ahoi hoi @neuromusic,

thanks a lot for the feedback. You're definitely right that only including `docker pull peerherholz/bidsonym:version` will lead to problems. However, to also prevent `copy paste errors/problems` via including only certain examples for specific versions (e.g.  `docker pull peerherholz/bidsonym:version`), I extended the respective part(s) of the documentation to include and explain both the `place holder` and the `specific version` option. Furthermore, the section related to `Singularity` was updated and `markup` related problems fixed. 

Thanks again!
