### ISSUE TITLE
Default should not be to overwrite files

### ISSUE THREAD

**Issue by kdestasio** [PeerHerholz/BIDSonym#8]
### Summary
The default for `--del_nodeface {del,no_del}` is to overwrite and delete original data. Setting the default to alter the original data sets up users (esp. less experienced users) for potential problems. Would be better to set the default to `no_del` to copy the original data to different folder.

### Actual behavior
Delete original data as default. 

### Expected behavior
Require user input to delete original data.

### Script/Workflow details

Please put URL to code or code here (if not too long).

### Platform details:

```

```

### Execution environment

Choose one
- Container [Tag: ???]
- My python environment inside container [Base Tag: ???]
- My python environment outside container

**Comment by PeerHerholz** [comment]
Hey @kdestasio,

thx very much for pointing us towards this. You're absolutely right.
I'll change it and get back as soon as the docker is successfully build.

**Comment by PeerHerholz** [comment]
Should be solved with the changes done [here](https://github.com/PeerHerholz/BIDSonym/commit/fdfc872d67a98d9956d85dc36b0c99a46c0ed95b). Hence, I'm closing this issue.
